spring.application.name=imdb-info-hub

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:imdbdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test

# Local data files (classpath)
imdb.data.name=classpath:static/data/name.basics.tsv.gz
imdb.data.title=classpath:static/data/title.basics.tsv.gz
imdb.data.crew=classpath:static/data/title.crew.tsv.gz
imdb.data.ratings=classpath:static/data/title.ratings.tsv.gz
imdb.data.principals=classpath:static/data/title.principals.tsv.gz